"""Update sql knowledge base table

Revision ID: 5ab9504d40df
Revises: b218a70fac43
Create Date: 2024-05-16 00:02:53.783090

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "5ab9504d40df"
down_revision = "b218a70fac43"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "monkey_tools_knowledge_bases_sql_knowledge_bases", schema=None
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                "type", sa.String(length=255), nullable=True, server_default="builtIn"
            )
        )
        batch_op.add_column(sa.Column("host", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("port", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("username", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("password", sa.String(length=255), nullable=True))
        batch_op.add_column(
            sa.Column(
                "schema", sa.String(length=255), nullable=True, server_default="public"
            )
        )
        batch_op.add_column(sa.Column("database", sa.String(length=255), nullable=True))
        batch_op.add_column(
            sa.Column("database_type", sa.String(length=255), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "monkey_tools_knowledge_bases_sql_knowledge_bases", schema=None
    ) as batch_op:
        batch_op.drop_column("database")
        batch_op.drop_column("schema")
        batch_op.drop_column("password")
        batch_op.drop_column("username")
        batch_op.drop_column("port")
        batch_op.drop_column("host")
        batch_op.drop_column("type")
        batch_op.drop_column("database_type")
    # ### end Alembic commands ###
