"""Initial migration.

Revision ID: b218a70fac43
Revises: 
Create Date: 2024-04-24 18:01:39.459520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b218a70fac43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monkey_tools_knowledge_base_documents',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('knowledge_base_id', postgresql.UUID(), nullable=True),
    sa.Column('index_status', sa.String(), nullable=True),
    sa.Column('failed_message', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='document_pkey')
    )
    op.create_table('monkey_tools_knowledge_base_metadata_fields',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('knowledge_base_id', postgresql.UUID(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='metadata_fields_pkey')
    )
    op.create_table('monkey_tools_knowledge_base_tasks',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('knowledge_base_id', postgresql.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('progress', sa.DECIMAL(), nullable=True),
    sa.Column('latest_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='task_pkey')
    )
    op.create_table('monkey_tools_knowledge_bases',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('dimension', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='knowledge_base_pkey')
    )
    op.create_table('monkey_tools_knowledge_bases_sql_knowledge_bases',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='sql_knowledge_base_pkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monkey_tools_knowledge_bases_sql_knowledge_bases')
    op.drop_table('monkey_tools_knowledge_bases')
    op.drop_table('monkey_tools_knowledge_base_tasks')
    op.drop_table('monkey_tools_knowledge_base_metadata_fields')
    op.drop_table('monkey_tools_knowledge_base_documents')
    # ### end Alembic commands ###
